import { createClient } from "@/lib/supabase/server";

export async function recordOpportunityFeedback(input: {
  workspaceId: string;
  samOpportunityId: string;
  eventType:
    | "viewed"
    | "saved"
    | "dismissed"
    | "pursued"
    | "promoted"
    | "override_set"
    | "override_cleared";
  priorRecommendation?: string;
  reasonTag?: string;
  metadata?: Record<string, unknown>;
  actorUserId?: string;
}) {
  const supabase = await createClient();
  const { error } = await supabase.from("opportunity_feedback_events").insert({
    workspace_id: input.workspaceId,
    sam_opportunity_id: input.samOpportunityId,
    event_type: input.eventType,
    prior_recommendation: input.priorRecommendation || null,
    reason_tag: input.reasonTag || null,
    metadata: input.metadata || {},
    actor_user_id: input.actorUserId || null,
  });

  if (error) throw new Error(error.message);
}

export async function getWorkspaceFeedbackMetrics(workspaceId: string, lookbackDays = 30) {
  const supabase = await createClient();
  const since = new Date(Date.now() - lookbackDays * 24 * 60 * 60 * 1000).toISOString();

  const { data: events, error } = await supabase
    .from("opportunity_feedback_events")
    .select("event_type,reason_tag,created_at")
    .eq("workspace_id", workspaceId)
    .gte("created_at", since);

  if (error) throw new Error(error.message);

  const rows = events || [];
  const counts = rows.reduce<Record<string, number>>((acc, row) => {
    acc[row.event_type] = (acc[row.event_type] || 0) + 1;
    return acc;
  }, {});

  const saved = counts.saved || 0;
  const pursued = counts.pursued || 0;
  const dismissed = counts.dismissed || 0;
  const viewed = counts.viewed || 0;

  const acceptanceRate = viewed === 0 ? 0 : Number(((saved + pursued) / viewed).toFixed(4));
  const dismissalRate = viewed === 0 ? 0 : Number((dismissed / viewed).toFixed(4));

  const topDismissReasons = Object.entries(
    rows
      .filter((row) => row.event_type === "dismissed" && row.reason_tag)
      .reduce<Record<string, number>>((acc, row) => {
        const key = row.reason_tag || "unspecified";
        acc[key] = (acc[key] || 0) + 1;
        return acc;
      }, {})
  )
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([reason, count]) => ({ reason, count }));

  return {
    lookbackDays,
    totalEvents: rows.length,
    counts,
    acceptanceRate,
    dismissalRate,
    topDismissReasons,
  };
}

export async function runWorkspaceCalibration(workspaceId: string, actorUserId?: string) {
  const supabase = await createClient();
  const metrics = await getWorkspaceFeedbackMetrics(workspaceId, 45);

  const { data: latestConfig } = await supabase
    .from("scoring_model_configs")
    .select("version,pursue_threshold,monitor_threshold,exploration_ratio,deterministic_weights")
    .eq("workspace_id", workspaceId)
    .order("version", { ascending: false })
    .limit(1)
    .maybeSingle();

  const nextVersion = (latestConfig?.version || 0) + 1;

  const proposedPursueThreshold = metrics.dismissalRate > 0.5 ? 80 : 75;
  const proposedMonitorThreshold = metrics.acceptanceRate < 0.15 ? 55 : 50;
  const proposedExplorationRatio = metrics.totalEvents < 50 ? 0.3 : 0.2;

  const proposedConfig = {
    pursueThreshold: proposedPursueThreshold,
    monitorThreshold: proposedMonitorThreshold,
    explorationRatio: proposedExplorationRatio,
    deterministicWeights: latestConfig?.deterministic_weights || {
      naics: 0.35,
      setAside: 0.25,
      agency: 0.15,
      timeline: 0.15,
      psc: 0.1,
    },
  };

  await supabase.from("scoring_calibration_runs").insert({
    workspace_id: workspaceId,
    config_version: nextVersion,
    baseline_metrics: metrics,
    proposed_metrics: {
      targetAcceptanceRate: metrics.acceptanceRate,
      targetDismissalRate: metrics.dismissalRate,
    },
    proposed_config: proposedConfig,
    applied: false,
  });

  await supabase.from("scoring_model_configs").insert({
    workspace_id: workspaceId,
    version: nextVersion,
    deterministic_weights: proposedConfig.deterministicWeights,
    pursue_threshold: proposedPursueThreshold,
    monitor_threshold: proposedMonitorThreshold,
    exploration_ratio: proposedExplorationRatio,
    notes: "Auto-generated by calibration run",
    created_by: actorUserId || null,
  });

  return {
    version: nextVersion,
    baseline: metrics,
    proposedConfig,
  };
}
